### ISSUE TITLE
Bits emotes showing up in channel emotes.

### ISSUE THREAD

**Issue by OlleSan** [rcwdev/emote-showcase#1]
Could you make it possible to disable bits emotes from showing up in channel emotes? Would be nice to put them in a separate category.
Same could be done with T2 and T3 perhaps as well.
The showcase could still be grouped if enabled or if you want to completely separate them, put them in their own showcase group, your design choice.

**Comment by rcwdev** [comment]
This is something I've been thinking about adding for quite some time, I just don't work on this project very often. It will likely be an option between having all of them grouped under one tab, or separating each type of emote (including animated).

**Comment by rcwdev** [comment]
This feature has finally been implemented as of 617bacbc6c70b8cae2a40c45af8770913e7c975a's commit. The updated extension (1.3.0) is in review by Twitch and will hopefully be released in January of 2023!

PogChamp
